# Generated by Django 4.0.4 on 2022-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=20)),
                ('Modelo', models.CharField(max_length=20)),
                ('Valor', models.IntegerField()),
            ],
        ),
    ]
